apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflow-deployment-{{ .Values.env }}
  labels:
    app: cloudflow
    env: {{ .Values.env }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflow
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: cloudflow
        env: {{ .Values.env }}
    spec:
      containers:
        - name: cloudflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
