replicaCount: 1

env: "main" 

image:
  repository: 261303806788.dkr.ecr.us-east-1.amazonaws.com/myprojectsrepos/cloudflow
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000  

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: cloudflow.me
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cloudflow-tls
      hosts:
        - cloudflow.me

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 5000  

readinessProbe:
  httpGet:
    path: /
    port: 5000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

